# Generated by Django 4.0.6 on 2022-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='img/')),
                ('cost', models.FloatField()),
                ('volume', models.FloatField()),
                ('info', models.TextField()),
            ],
        ),
    ]
