# Generated by Django 4.0.6 on 2022-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_catalog_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-01 00:00'),
            preserve_default=False,
        ),
    ]
