# Generated by Django 4.0.6 on 2022-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
