# Generated by Django 4.0.6 on 2022-08-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_blog_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='created_on',
        ),
    ]
